color0 #031f3a
color1 #fd4663
color2 #60ccfe
color3 #607dfe
color4 #9260fe
color5 #80d6fe
color6 #8097fe
color7 #f2f2f3
color8 #5d6b71
color9 #fd4663
color10 #60ccfe
color11 #607dfe
color12 #9260fe
color13 #80d6fe
color14 #8097fe
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #031f3a
background            #031f3a
foreground            #f2f2f3
selection_foreground  #afb4b6
selection_background  #082a49
active_border_color   #60ccfe
inactive_border_color #082a49
url_color             #60ccfe

active_tab_foreground   #182125
active_tab_background   #60ccfe
inactive_tab_foreground #afb4b6
inactive_tab_background #082a49
cursor_trail_color      #afb4b6
