cursor            #ffb3ad
cursor_text_color #571e1b

foreground            #f1dedc
background            #140c0b
selection_foreground  #442927
selection_background  #e7bdb9
url_color             #e7bdb9

#: black 000000 767676
color0  #1a1110
color8  #3d3231
#: red cc0403 f2201f
color1  #270b0b
color9  #9f2c2d
#: green 19cb00 23fd00
color2  #e7bdb9
color10 #ffdad6
#: yellow cecb00 fffd00
color3  #e1c28c
color11 #fedea6
#: blue 0d73cc 1a8fff
color4  #73332f
color12 #ffb3ad
#: magenta cb1ed1 fd28ff
color5  #5d3f3c
color13 #e7bdb9
#: cyan 0dcdcd 14ffff
color6  #584419
color14 #e1c28c
#: white dddddd ffffff
color7  #d8c2bf
color15 #f1dedc

mark1_foreground #3b0908
mark1_background #ffdad6
mark2_foreground #2c1513
mark2_background #ffdad6
mark3_foreground #261900
mark3_background #fedea6

active_tab_foreground #571e1b
active_tab_background #ffb3ad
inactive_tab_foreground #ffdad6
inactive_tab_background #73332f

active_border_color #ffb3ad
inactive_border_color #571e1b
# bell_border_color #ff5a00
