cursor            #e8b5ef
cursor_text_color #472150

foreground            #eae0e7
background            #110d11
selection_foreground  #3a2b3c
selection_background  #d6c0d6
url_color             #d6c0d6

#: black 000000 767676
color0  #171217
color8  #393338
#: red cc0403 f2201f
color1  #a01ab2
color9  #de7aec
#: green 19cb00 23fd00
color2  #d6c0d6
color10 #f3dbf2
#: yellow cecb00 fffd00
color3  #f5b7b0
color11 #ffdad6
#: blue 0d73cc 1a8fff
color4  #603768
color12 #e8b5ef
#: magenta cb1ed1 fd28ff
color5  #524153
color13 #d6c0d6
#: cyan 0dcdcd 14ffff
color6  #673b36
color14 #f5b7b0
#: white dddddd ffffff
color7  #cfc3cd
color15 #eae0e7

mark1_foreground #300a3a
mark1_background #fcd6ff
mark2_foreground #241727
mark2_background #f3dbf2
mark3_foreground #33110e
mark3_background #ffdad6

active_tab_foreground #472150
active_tab_background #e8b5ef
inactive_tab_foreground #fcd6ff
inactive_tab_background #603768

active_border_color #e8b5ef
inactive_border_color #472150
# bell_border_color #ff5a00
