cursor            #96ccf8
cursor_text_color #00344f

foreground            #e0e3e8
background            #0b0f12
selection_foreground  #22323f
selection_background  #b8c8d9
url_color             #b8c8d9

#: black 000000 767676
color0  #101417
color8  #313539
#: red cc0403 f2201f
color1  #1e2e3a
color9  #517fa0
#: green 19cb00 23fd00
color2  #b8c8d9
color10 #d3e5f6
#: yellow cecb00 fffd00
color3  #d0c0e8
color11 #ebdcff
#: blue 0d73cc 1a8fff
color4  #004b70
color12 #96ccf8
#: magenta cb1ed1 fd28ff
color5  #394956
color13 #b8c8d9
#: cyan 0dcdcd 14ffff
color6  #4d4162
color14 #d0c0e8
#: white dddddd ffffff
color7  #c1c7ce
color15 #e0e3e8

mark1_foreground #001e30
mark1_background #cae6ff
mark2_foreground #0c1d29
mark2_background #d3e5f6
mark3_foreground #211634
mark3_background #ebdcff

active_tab_foreground #00344f
active_tab_background #96ccf8
inactive_tab_foreground #cae6ff
inactive_tab_background #004b70

active_border_color #96ccf8
inactive_border_color #00344f
# bell_border_color #ff5a00
