#!/usr/bin/env python3

import os
import subprocess as sp
import random

if __name__ == '__main__':

    dir = '/home/pawritra/Pictures/Wallpapers/'
    items = os.listdir(dir)

    if len(items) <= 0:
      exit(0)

    random.shuffle(items)
    wallpaper = dir + items[0]

    sp.run(['awww', 'img', wallpaper])
    sp.run(['matugen', 'image', wallpaper, '--source-color-index', '0'])
    sp.run(['bash', '/home/pawritra/.config/waybar/scripts/launch.sh'])
