music_directory		"~/Store/Music"
playlist_directory		"~/Store/Music/.mpd/playlists"
db_file			"~/Store/Music/.mpd/mpd.db"
log_file			"~/Store/Music/.mpd/log"
pid_file			"~/Store/Music/.mpd/pid"
state_file			"~/Store/Music/.mpd/state"
sticker_file			"~/Store/Music/.mpd/sticker.sql"

auto_update        "yes"

input {
        plugin "curl"
#       proxy "proxy.isp.com:8080"
#       proxy_user "user"
#       proxy_password "password"
}

audio_output {
	type		"alsa"
	name		"My ALSA Device"
	# device		"hw:0,0"	# optional
	mixer_type      "hardware"	# optional
	mixer_device	"default"	# optional
	mixer_control	"PCM"		# optional
	mixer_index	"0"		# optional
}

audio_output {
   type   "fifo"
   name   "my_fifo"
   path   "/tmp/.mpd.fifo"
   format "44100:16:2"
}
